$RESIZE:SMOOTH
_TITLE "/// GRAPHIC LOOP TEST ///             RESIZE OR CLOSE WINDOW TO EXIT"
DEFSNG A-Z
SCREEN _NEWIMAGE(1280, 1024, 256): '_FULLSCREEN
CLS
_DISPLAY
BITSTATE = 1
VERTICALXMINI = 1
HORIZONTALYMINI = 1
VERTICALXMAXI = 1278
HORIZONTALYMAXI = 1023
LINESTOTAL = 35
COLORCODE = 15

START:

FOR LINESTOTAL = 20 TO 399
    CLS
    XS = (VERTICALXMAXI - VERTICALXMINI) / LINESTOTAL
    YS = (HORIZONTALYMAXI - HORIZONTALYMINI) / LINESTOTAL

    FOR OUTSIDELOOP = 0 TO LINESTOTAL
        IF INKEY$ <> "" THEN BITSTATE = BITSTATE + 1: IF BITSTATE > 1 THEN BITSTATE = 0
        SELECT CASE BITSTATE
            CASE 0
                LINE (VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMINI)-(VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMINI + YS * OUTSIDELOOP), 1
                LINE (VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMAXI)-(VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMAXI - YS * OUTSIDELOOP), 1
                LINE (VERTICALXMAXI, HORIZONTALYMINI + YS * OUTSIDELOOP)-(VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMAXI - YS * OUTSIDELOOP), 4
                LINE (VERTICALXMINI, HORIZONTALYMAXI - YS * OUTSIDELOOP)-(VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMINI + YS * OUTSIDELOOP), 4
            CASE 1
                LINE (VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMAXI)-(VERTICALXMAXI, HORIZONTALYMAXI - YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
                LINE (VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMINI)-(VERTICALXMAXI, HORIZONTALYMAXI - YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
                LINE (VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMINI)-(VERTICALXMINI, HORIZONTALYMINI + YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
                LINE (VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMAXI)-(VERTICALXMINI, HORIZONTALYMINI + YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
        END SELECT
    NEXT OUTSIDELOOP
    _DISPLAY
NEXT LINESTOTAL
FOR LINESTOTAL = 398 TO 19 STEP -1
    CLS
    XS = (VERTICALXMAXI - VERTICALXMINI) / LINESTOTAL
    YS = (HORIZONTALYMAXI - HORIZONTALYMINI) / LINESTOTAL

    FOR OUTSIDELOOP = 0 TO LINESTOTAL
        IF INKEY$ <> "" THEN BITSTATE = BITSTATE + 1: IF BITSTATE > 1 THEN BITSTATE = 0
        SELECT CASE BITSTATE
            CASE 0
                LINE (VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMINI)-(VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMINI + YS * OUTSIDELOOP), 1
                LINE (VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMAXI)-(VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMAXI - YS * OUTSIDELOOP), 1
                LINE (VERTICALXMAXI, HORIZONTALYMINI + YS * OUTSIDELOOP)-(VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMAXI - YS * OUTSIDELOOP), 4
                LINE (VERTICALXMINI, HORIZONTALYMAXI - YS * OUTSIDELOOP)-(VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMINI + YS * OUTSIDELOOP), 4
            CASE 1
                LINE (VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMAXI)-(VERTICALXMAXI, HORIZONTALYMAXI - YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
                LINE (VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMINI)-(VERTICALXMAXI, HORIZONTALYMAXI - YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
                LINE (VERTICALXMAXI - XS * OUTSIDELOOP, HORIZONTALYMINI)-(VERTICALXMINI, HORIZONTALYMINI + YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
                LINE (VERTICALXMINI + XS * OUTSIDELOOP, HORIZONTALYMAXI)-(VERTICALXMINI, HORIZONTALYMINI + YS * OUTSIDELOOP), COLORCODE + OUTSIDELOOP
        END SELECT
    NEXT OUTSIDELOOP
    _DISPLAY
NEXT LINESTOTAL
GOTO START
